# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Breicordados' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for Breicordados
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'
  pod 'FBSDKLoginKit'

  target 'Breicordados-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BreicordadosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Breicordados-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Breicordados-tvOS

end
