export const REQUEST_USER = "REQUEST_USER";
export const SET_USER_ORDERS = 'SET_USER_ORDERS'; 
export const GET_FECTHED_USER = {
    GET_USER_DATA: "GET_USER_DATA",
    GET_USER_RACKETS: "GET_USER_RACKETS",
    GET_USER_ORDERS: "GET_USER_ORDERS",
    GET_USER_ADDRESS:"GET_USER_ADDRESS"
};
export const ADD_USER_DATA = {
    ADD_RACKET: 'ADD_RACKET',
    REMOVE_RACKET: 'REMOVE_RACKET',
    ADD_ORDER: 'ADD_ORDER',
    ADD_ADDRES: 'ADD_ADDRES',
};
export const RECIVE_USER = "RECIVE_USER";
export const ADD_STRINGS = 'ADD_STRINGS';
export const RECIVE_USER_RACKETS = 'RECIVE_USER_RACKETS';
